### ISSUE TITLE
Saving failed rows

### ISSUE THREAD

**Issue by tombaeyens** [awslabs/deequ#111]
Hi,

Kudo's for the great project, folks.

When running a verification suite, is it somehow possible to save the rows that are failing for each check separately?  Or get a hold of the filtered dataset for each failing test?

Tnx

**Comment by sscdotopen** [comment]
Hi Tom,

Unfortunately, it is not always possible to (uniquely) identify the rows that made a check fail, especially if you write some custom validation code, therefore deequ does not support this functionality.

**Comment by Tauranis** [comment]
Sorry to say that, but for me this is non-sense, because the library scans the dataset to find the inconsistencies, so it should retrieve the failing rows.
Thus, one needs to do duplicate work, 1- check inconsistencies(on deequ) 2- find inconsistent rows(any other way).
I believe this should be a must-have feature.

**Comment by sscdotopen** [comment]
Hi Tauranis, 

Let me give you a few examples on why it is in general not possible to identify the "failed rows", in order to clarify my earlier comment:

1. Let's say you add a constraint in deequ that states that there should be 100 distinct values in a column, but during execution deequ finds 101 distinct values. How would we identify the "failing rows" here? We could remove **any** subset of rows with a common distinct value to satisfy the constraint.

1. Lets say you want the mean of a column to be smaller than a particular value. Again there could be many different subsets of rows that we could remove to satisfy the constraint.

1. Deequ allows users to write *arbitary Scala code* to evaluate a computed metric. We have heard from users who have different thresholds for the completeness of a column based on the day of the week. Deequ will not be able to reverse-engineer the validation semantics from arbitrary Scala code.

**Comment by sscdotopen** [comment]
I would like to highlight that we have a special class to find individual rows that violate simple constraints: https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/schema/RowLevelSchemaValidator.scala
