### ISSUE TITLE
AWS Glue job run error - TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by eladsela** [awslabs/deequ#423]
when using ColumnProfilerRunner function,
how do i solve it?

also I tried to work with this it on my mac - also same error

glue version 2.0 
spark 2.4 
python 3

**Comment by hjhardik** [comment]
This error usually occurs when the JAR itself is not successfully loaded in the execution environment. Please double-check whether the `deequ` JAR is correctly loaded in the Glue spark environment.

**Comment by mentekid** [comment]
Hi,

Thanks for opening this issue.

The error you are getting is because the feature is not available in Glue versions earlier than 3.0.

This GitHub repository is about Deequ, the Open Source project. While Deequ powers AWS Data Quality, we like to keep this forum separate and focused on the open source community. You can find support for Data Quality in the AWS forums and AWS support.
